---
- name: "webserver"
  hosts: web
  become: yes
  tags:
    - webservers
  tasks: 
  roles: 
    - webservers

# Enable this when we have an app to install
#- name: "Installing appserver"
#  hosts: app
#  become: yes
#  tags:
#    - start_appserver
#  tasks: 
#    - include_playbook: appserver.yml
#      tags: 
#        - install

- name: "Database"
  hosts: all
  become: yes
  tags:
    - database
  tasks: 
  roles: 
    - databases
