---
- name: Install apache
  yum:
    name: httpd
    state: installed
  tags:
    - install
- name: Stopping apache
  service:
    name: httpd
    state: stopped
  tags:
    - stop_webserver
- name: Starting apache
  service:
    name: httpd
    state: started
  tags:
    - install
    - start_webserver

