---
- name: Install mariadb
  yum:
    name: mariadb-server
    state: installed
  tags:
    - install

- name: Stopping mariadb
  service:
    name: mariadb
    state: stopped
  tags:
    - stop_database

- name: Start mariadb
  service:
    name: mariadb
    state: started
  tags:
    - install
    - start_database

